version: '3.8'

services:
  # Load Balancer / Reverse Proxy
  nginx:
    build: ./nginx
    container_name: cdn-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/certs
    depends_on:
      - edge-server-1
      - edge-server-2
      - api-gateway
    networks:
      - cdn-network

  # Edge Servers (Go)
  edge-server-1:
    build: ./edge-server
    container_name: cdn-edge-1
    environment:
      - EDGE_ID=edge-1
      - REDIS_URL=redis://redis-cluster:6379
      - ORIGIN_URL=http://origin-server:3000
      - REGION=us-east-1
    depends_on:
      - redis-cluster
      - origin-server
    networks:
      - cdn-network

  edge-server-2:
    build: ./edge-server
    container_name: cdn-edge-2
    environment:
      - EDGE_ID=edge-2
      - REDIS_URL=redis://redis-cluster:6379
      - ORIGIN_URL=http://origin-server:3000
      - REGION=us-west-1
    depends_on:
      - redis-cluster
      - origin-server
    networks:
      - cdn-network

  # Origin Server (Node.js)
  origin-server:
    build: ./origin-server
    container_name: cdn-origin
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_URL=postgresql://cdn_user:cdn_password@postgres:5432/cdn_db
      - REDIS_URL=redis://redis-cluster:6379
      - INFLUX_URL=http://influxdb:8086
    volumes:
      - ./origin-server/uploads:/app/uploads
    depends_on:
      - postgres
      - redis-cluster
    networks:
      - cdn-network

  # API Gateway (Node.js)
  api-gateway:
    build: ./api-gateway
    container_name: cdn-api-gateway
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DB_URL=postgresql://cdn_user:cdn_password@postgres:5432/cdn_db
    depends_on:
      - postgres
    networks:
      - cdn-network

  # Analytics Service (Python)
  analytics-service:
    build: ./analytics-service
    container_name: cdn-analytics
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=your-influx-token
      - INFLUX_ORG=cdn-org
      - INFLUX_BUCKET=cdn-analytics
    depends_on:
      - influxdb
    networks:
      - cdn-network

  # Databases
  postgres:
    image: postgres:15-alpine
    container_name: cdn-postgres
    environment:
      - POSTGRES_DB=cdn_db
      - POSTGRES_USER=cdn_user
      - POSTGRES_PASSWORD=cdn_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - cdn-network

  redis-cluster:
    image: redis:7-alpine
    container_name: cdn-redis
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - redis_data:/data
      - ./database/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - cdn-network

  # Time Series Database for Analytics
  influxdb:
    image: influxdb:2.7-alpine
    container_name: cdn-influxdb
    environment:
      - INFLUXDB_DB=cdn_analytics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_USER=cdn_user
      - INFLUXDB_USER_PASSWORD=cdn_password
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - cdn-network

  # Monitoring
  prometheus:
    build: ./monitoring/prometheus
    container_name: cdn-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - cdn-network

  grafana:
    build: ./monitoring/grafana
    container_name: cdn-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - influxdb
    networks:
      - cdn-network

volumes:
  postgres_data:
  redis_data:
  influxdb_data:
  prometheus_data:
  grafana_data:

networks:
  cdn-network:
    driver: bridge