# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Edge servers
  - job_name: 'edge-servers'
    static_configs:
      - targets: 
        - 'edge-server-1:8080'
        - 'edge-server-2:8080'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Origin server
  - job_name: 'origin-server'
    static_configs:
      - targets: ['origin-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Analytics service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cluster:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # InfluxDB
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
    scrape_interval: 15s

# Alert rules
rule_files:
  - "/etc/prometheus/alert_rules.yml"

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB