apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: cdn-system
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: cdn-analytics-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: INFLUX_URL
          valueFrom:
            configMapKeyRef:
              name: cdn-config
              key: INFLUX_URL
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: cdn-secrets
              key: influx-token
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: cdn-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
