apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: cdn-system
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: analytics-service
