apiVersion: v1
kind: Service
metadata:
  name: edge-server
  namespace: cdn-system
  labels:
    app: edge-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: edge-server
