apiVersion: v1
kind: Service
metadata:
  name: origin-server
  namespace: cdn-system
  labels:
    app: origin-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: origin-server
