apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: cdn-system
  labels:
    app: redis-cluster
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis-cluster
